import { useTranslation } from 'react-i18next';

const keys = ['resumeTitle', 'savedAt', 'resume', 'downloadBackup', 'delete', 'deviceNotice',
  'loadFailed', 'saving', 'saved', 'conflict', 'saveFailed', 'reloadLatest', 'remember',
  'replacePrompt', 'replace', 'cancel'] as const;
type Key = typeof keys[number];

const historyNotice: Record<string, string> = {
  en: 'Older undo steps were removed to keep this project manageable.',
  ar: 'حُذفت خطوات التراجع القديمة للحفاظ على حجم المشروع.',
  ca: 'S’han eliminat passos antics de desfer per limitar la mida del projecte.',
  cs: 'Starší kroky zpět byly odebrány kvůli velikosti projektu.',
  de: 'Ältere Rückgängig-Schritte wurden entfernt, um die Projektgröße zu begrenzen.',
  el: 'Παλαιότερα βήματα αναίρεσης αφαιρέθηκαν για να περιοριστεί το μέγεθος του έργου.',
  es: 'Se eliminaron pasos antiguos de deshacer para limitar el tamaño del proyecto.',
  fr: 'D’anciennes étapes d’annulation ont été supprimées pour limiter la taille du projet.',
  hu: 'A projekt méretének korlátozása érdekében a régebbi visszavonási lépések törlődtek.',
  id: 'Langkah urungkan lama dihapus untuk membatasi ukuran proyek.',
  it: 'Alcuni passaggi di annullamento precedenti sono stati rimossi per limitare le dimensioni del progetto.',
  ja: 'プロジェクトのサイズを抑えるため、古い元に戻す履歴を削除しました。',
  ko: '프로젝트 크기를 제한하기 위해 오래된 실행 취소 기록을 삭제했습니다.',
  nl: 'Oudere ongedaanmaakstappen zijn verwijderd om het project klein te houden.',
  pcm: 'Old undo steps don go so di project no go too big.',
  pl: 'Starsze kroki cofania usunięto, aby ograniczyć rozmiar projektu.',
  'pt-BR': 'Etapas antigas de desfazer foram removidas para limitar o tamanho do projeto.',
  ru: 'Старые шаги отмены удалены, чтобы ограничить размер проекта.',
  sv: 'Äldre ångringssteg har tagits bort för att begränsa projektets storlek.',
  tr: 'Proje boyutunu sınırlamak için eski geri alma adımları kaldırıldı.',
  uk: 'Старі кроки скасування видалено, щоб обмежити розмір проєкту.',
  zh: '为控制项目大小，较早的撤销记录已被移除。',
};

// The project flow has the same language coverage as the main editor. Keep these
// short strings together so the save and conflict states cannot drift by locale.
const messages: Record<string, string[]> = {
  en: ['Resume last project', 'Last saved: {date}', 'Resume', 'Download backup', 'Delete saved project', 'This project is saved in this browser on this device. Clearing site data may remove it.', 'Could not load project', 'Saving…', 'Saved on this device', 'Another tab saved a newer version.', 'Couldn’t save — download a project file', 'Reload latest', 'Remember this project on this device', 'Replacing this project will overwrite the saved project. Download a backup first if needed.', 'Replace saved project', 'Cancel'],
  ar: ['استئناف آخر مشروع', 'آخر حفظ: {date}', 'استئناف', 'تنزيل نسخة احتياطية', 'حذف المشروع المحفوظ', 'هذا المشروع محفوظ في هذا المتصفح على هذا الجهاز. قد تؤدي إزالة بيانات الموقع إلى حذفه.', 'تعذر تحميل المشروع', 'جارٍ الحفظ…', 'تم الحفظ على هذا الجهاز', 'حفظت علامة تبويب أخرى نسخة أحدث.', 'تعذر الحفظ — نزّل ملف المشروع', 'تحميل الأحدث', 'تذكّر هذا المشروع على هذا الجهاز', 'سيؤدي الاستبدال إلى الكتابة فوق المشروع المحفوظ. نزّل نسخة احتياطية عند الحاجة.', 'استبدال المشروع', 'إلغاء'],
  ca: ['Reprèn el darrer projecte', 'Desat per darrer cop: {date}', 'Reprèn', 'Baixa una còpia', 'Suprimeix el projecte desat', 'Aquest projecte es desa en aquest navegador i dispositiu. Si esborres les dades del lloc, el pots perdre.', 'No s’ha pogut carregar el projecte', 'Desant…', 'Desat en aquest dispositiu', 'Una altra pestanya ha desat una versió més nova.', 'No s’ha pogut desar — baixa el fitxer del projecte', 'Carrega la versió més recent', 'Recorda aquest projecte al dispositiu', 'Substituir-lo sobreescriurà el projecte desat. Baixa una còpia si cal.', 'Substitueix el projecte', 'Cancel·la'],
  cs: ['Pokračovat v posledním projektu', 'Naposledy uloženo: {date}', 'Pokračovat', 'Stáhnout zálohu', 'Smazat uložený projekt', 'Projekt je uložen v tomto prohlížeči a zařízení. Vymazání dat webu jej může odstranit.', 'Projekt nelze načíst', 'Ukládání…', 'Uloženo v tomto zařízení', 'Jiná karta uložila novější verzi.', 'Nelze uložit — stáhněte soubor projektu', 'Načíst nejnovější', 'Pamatovat projekt v tomto zařízení', 'Nahrazení přepíše uložený projekt. V případě potřeby stáhněte zálohu.', 'Nahradit projekt', 'Zrušit'],
  de: ['Letztes Projekt fortsetzen', 'Zuletzt gespeichert: {date}', 'Fortsetzen', 'Sicherung herunterladen', 'Gespeichertes Projekt löschen', 'Dieses Projekt liegt in diesem Browser auf diesem Gerät. Beim Löschen der Websitedaten kann es verloren gehen.', 'Projekt konnte nicht geladen werden', 'Wird gespeichert…', 'Auf diesem Gerät gespeichert', 'Ein anderer Tab hat eine neuere Version gespeichert.', 'Speichern fehlgeschlagen — Projektdatei herunterladen', 'Neueste Version laden', 'Projekt auf diesem Gerät merken', 'Beim Ersetzen wird das gespeicherte Projekt überschrieben. Laden Sie bei Bedarf eine Sicherung herunter.', 'Projekt ersetzen', 'Abbrechen'],
  el: ['Συνέχεια τελευταίου έργου', 'Τελευταία αποθήκευση: {date}', 'Συνέχεια', 'Λήψη αντιγράφου', 'Διαγραφή αποθηκευμένου έργου', 'Το έργο αποθηκεύεται σε αυτό το πρόγραμμα περιήγησης και τη συσκευή. Η διαγραφή δεδομένων ιστότοπου μπορεί να το αφαιρέσει.', 'Αδυναμία φόρτωσης έργου', 'Αποθήκευση…', 'Αποθηκεύτηκε στη συσκευή', 'Άλλη καρτέλα αποθήκευσε νεότερη έκδοση.', 'Αδυναμία αποθήκευσης — κατεβάστε αρχείο έργου', 'Φόρτωση νεότερης', 'Απομνημόνευση έργου στη συσκευή', 'Η αντικατάσταση θα γράψει πάνω από το αποθηκευμένο έργο. Κατεβάστε αντίγραφο αν χρειάζεται.', 'Αντικατάσταση έργου', 'Άκυρο'],
  es: ['Reanudar el último proyecto', 'Último guardado: {date}', 'Reanudar', 'Descargar copia', 'Eliminar proyecto guardado', 'Este proyecto se guarda en este navegador y dispositivo. Al borrar los datos del sitio puede perderse.', 'No se pudo cargar el proyecto', 'Guardando…', 'Guardado en este dispositivo', 'Otra pestaña guardó una versión más reciente.', 'No se pudo guardar — descarga el archivo del proyecto', 'Cargar la versión más reciente', 'Recordar este proyecto en el dispositivo', 'Al reemplazarlo se sobrescribirá el proyecto guardado. Descarga una copia si la necesitas.', 'Reemplazar proyecto', 'Cancelar'],
  fr: ['Reprendre le dernier projet', 'Dernier enregistrement : {date}', 'Reprendre', 'Télécharger une sauvegarde', 'Supprimer le projet enregistré', 'Ce projet est enregistré dans ce navigateur sur cet appareil. Effacer les données du site peut le supprimer.', 'Impossible de charger le projet', 'Enregistrement…', 'Enregistré sur cet appareil', 'Un autre onglet a enregistré une version plus récente.', 'Enregistrement impossible — téléchargez le fichier du projet', 'Charger la dernière version', 'Mémoriser ce projet sur cet appareil', 'Le remplacement écrasera le projet enregistré. Téléchargez une sauvegarde si nécessaire.', 'Remplacer le projet', 'Annuler'],
  hu: ['Utolsó projekt folytatása', 'Utoljára mentve: {date}', 'Folytatás', 'Biztonsági másolat letöltése', 'Mentett projekt törlése', 'A projekt ebben a böngészőben, ezen az eszközön van mentve. A webhelyadatok törlése eltávolíthatja.', 'A projekt nem tölthető be', 'Mentés…', 'Mentve ezen az eszközön', 'Egy másik lap újabb verziót mentett.', 'Nem sikerült menteni — töltse le a projektfájlt', 'Legújabb betöltése', 'Projekt megjegyzése ezen az eszközön', 'A csere felülírja a mentett projektet. Szükség esetén töltsön le másolatot.', 'Projekt cseréje', 'Mégse'],
  id: ['Lanjutkan proyek terakhir', 'Terakhir disimpan: {date}', 'Lanjutkan', 'Unduh cadangan', 'Hapus proyek tersimpan', 'Proyek ini disimpan di browser dan perangkat ini. Menghapus data situs dapat menghapusnya.', 'Gagal memuat proyek', 'Menyimpan…', 'Tersimpan di perangkat ini', 'Tab lain menyimpan versi yang lebih baru.', 'Gagal menyimpan — unduh berkas proyek', 'Muat versi terbaru', 'Ingat proyek ini di perangkat', 'Mengganti akan menimpa proyek tersimpan. Unduh cadangan jika perlu.', 'Ganti proyek', 'Batal'],
  it: ['Riprendi l’ultimo progetto', 'Ultimo salvataggio: {date}', 'Riprendi', 'Scarica backup', 'Elimina progetto salvato', 'Il progetto è salvato in questo browser su questo dispositivo. Cancellare i dati del sito può rimuoverlo.', 'Impossibile caricare il progetto', 'Salvataggio…', 'Salvato su questo dispositivo', 'Un’altra scheda ha salvato una versione più recente.', 'Impossibile salvare — scarica il file del progetto', 'Carica la versione più recente', 'Ricorda il progetto su questo dispositivo', 'La sostituzione sovrascriverà il progetto salvato. Scarica un backup se serve.', 'Sostituisci progetto', 'Annulla'],
  ja: ['前回のプロジェクトを再開', '最終保存: {date}', '再開', 'バックアップをダウンロード', '保存したプロジェクトを削除', 'このプロジェクトは、この端末のブラウザーに保存されます。サイトデータを消すと削除される場合があります。', 'プロジェクトを読み込めません', '保存中…', 'この端末に保存済み', '別のタブで新しい版が保存されました。', '保存できません — プロジェクトファイルをダウンロードしてください', '最新版を読み込む', 'この端末にプロジェクトを保存', '置き換えると保存済みのプロジェクトが上書きされます。必要ならバックアップをダウンロードしてください。', 'プロジェクトを置き換える', 'キャンセル'],
  ko: ['마지막 프로젝트 다시 시작', '마지막 저장: {date}', '다시 시작', '백업 다운로드', '저장된 프로젝트 삭제', '이 프로젝트는 이 기기의 브라우저에 저장됩니다. 사이트 데이터를 지우면 삭제될 수 있습니다.', '프로젝트를 불러올 수 없습니다', '저장 중…', '이 기기에 저장됨', '다른 탭에서 최신 버전을 저장했습니다.', '저장할 수 없음 — 프로젝트 파일을 다운로드하세요', '최신 버전 불러오기', '이 기기에 프로젝트 기억', '교체하면 저장된 프로젝트를 덮어씁니다. 필요하면 백업을 다운로드하세요.', '프로젝트 교체', '취소'],
  nl: ['Laatste project hervatten', 'Laatst opgeslagen: {date}', 'Hervatten', 'Back-up downloaden', 'Opgeslagen project verwijderen', 'Dit project staat in deze browser op dit apparaat. Het wissen van sitegegevens kan het verwijderen.', 'Project kan niet worden geladen', 'Opslaan…', 'Opgeslagen op dit apparaat', 'Een ander tabblad heeft een nieuwere versie opgeslagen.', 'Opslaan mislukt — download het projectbestand', 'Nieuwste versie laden', 'Project onthouden op dit apparaat', 'Vervangen overschrijft het opgeslagen project. Download zo nodig een back-up.', 'Project vervangen', 'Annuleren'],
  pcm: ['Continue di last project', 'Last save: {date}', 'Continue', 'Download backup', 'Delete saved project', 'Dis project dey for dis browser for dis device. If you clear site data, e fit disappear.', 'Project no load', 'Dey save…', 'E don save for dis device', 'Another tab don save newer version.', 'E no save — download project file', 'Load di latest one', 'Remember dis project for dis device', 'If you replace am, e go overwrite di saved project. Download backup if you need am.', 'Replace project', 'Cancel'],
  pl: ['Wznów ostatni projekt', 'Ostatni zapis: {date}', 'Wznów', 'Pobierz kopię zapasową', 'Usuń zapisany projekt', 'Projekt jest zapisany w tej przeglądarce na tym urządzeniu. Usunięcie danych witryny może go skasować.', 'Nie udało się wczytać projektu', 'Zapisywanie…', 'Zapisano na tym urządzeniu', 'Inna karta zapisała nowszą wersję.', 'Nie udało się zapisać — pobierz plik projektu', 'Wczytaj najnowszą wersję', 'Zapamiętaj projekt na tym urządzeniu', 'Zastąpienie nadpisze zapisany projekt. W razie potrzeby pobierz kopię.', 'Zastąp projekt', 'Anuluj'],
  'pt-BR': ['Retomar o último projeto', 'Salvo pela última vez: {date}', 'Retomar', 'Baixar backup', 'Excluir projeto salvo', 'Este projeto fica salvo neste navegador e dispositivo. Limpar os dados do site pode removê-lo.', 'Não foi possível carregar o projeto', 'Salvando…', 'Salvo neste dispositivo', 'Outra aba salvou uma versão mais recente.', 'Não foi possível salvar — baixe o arquivo do projeto', 'Carregar versão mais recente', 'Lembrar deste projeto no dispositivo', 'A substituição sobrescreverá o projeto salvo. Baixe um backup se necessário.', 'Substituir projeto', 'Cancelar'],
  ru: ['Продолжить последний проект', 'Последнее сохранение: {date}', 'Продолжить', 'Скачать копию', 'Удалить сохранённый проект', 'Проект хранится в этом браузере на этом устройстве. Очистка данных сайта может удалить его.', 'Не удалось загрузить проект', 'Сохранение…', 'Сохранено на этом устройстве', 'Другая вкладка сохранила более новую версию.', 'Не удалось сохранить — скачайте файл проекта', 'Загрузить последнюю версию', 'Запомнить проект на устройстве', 'Замена перезапишет сохранённый проект. При необходимости скачайте копию.', 'Заменить проект', 'Отмена'],
  sv: ['Återuppta senaste projektet', 'Senast sparat: {date}', 'Återuppta', 'Ladda ned säkerhetskopia', 'Ta bort sparat projekt', 'Projektet sparas i den här webbläsaren på den här enheten. Om webbplatsdata rensas kan det försvinna.', 'Projektet kunde inte läsas in', 'Sparar…', 'Sparat på den här enheten', 'En annan flik har sparat en nyare version.', 'Kunde inte spara — ladda ned projektfilen', 'Läs in senaste versionen', 'Kom ihåg projektet på enheten', 'Ett byte skriver över det sparade projektet. Ladda ned en kopia vid behov.', 'Ersätt projektet', 'Avbryt'],
  tr: ['Son projeye devam et', 'Son kayıt: {date}', 'Devam et', 'Yedeği indir', 'Kayıtlı projeyi sil', 'Bu proje bu cihazdaki tarayıcıda saklanır. Site verilerini silmek projeyi kaldırabilir.', 'Proje yüklenemedi', 'Kaydediliyor…', 'Bu cihaza kaydedildi', 'Başka bir sekme daha yeni bir sürüm kaydetti.', 'Kaydedilemedi — proje dosyasını indirin', 'En yenisini yükle', 'Bu cihazda projeyi hatırla', 'Değiştirmek kayıtlı projenin üzerine yazacak. Gerekirse yedek indirin.', 'Projeyi değiştir', 'İptal'],
  uk: ['Продовжити останній проєкт', 'Останнє збереження: {date}', 'Продовжити', 'Завантажити копію', 'Видалити збережений проєкт', 'Проєкт зберігається в цьому браузері на цьому пристрої. Очищення даних сайту може його видалити.', 'Не вдалося завантажити проєкт', 'Збереження…', 'Збережено на цьому пристрої', 'Інша вкладка зберегла новішу версію.', 'Не вдалося зберегти — завантажте файл проєкту', 'Завантажити найновіше', 'Запам’ятати проєкт на пристрої', 'Заміна перезапише збережений проєкт. За потреби завантажте копію.', 'Замінити проєкт', 'Скасувати'],
  zh: ['继续上次的项目', '上次保存：{date}', '继续', '下载备份', '删除已保存项目', '此项目保存在本设备的此浏览器中。清除网站数据可能会将其删除。', '无法加载项目', '正在保存…', '已保存到本设备', '另一个标签页保存了更新的版本。', '无法保存——请下载项目文件', '加载最新版本', '在本设备记住此项目', '替换将覆盖已保存的项目。如有需要，请先下载备份。', '替换项目', '取消'],
};

export function useProjectMessage() {
  const { i18n } = useTranslation();
  const language = i18n.language in messages ? i18n.language : i18n.language.split('-')[0];
  const values = messages[language] ?? messages.en;
  return (key: Key, date?: string) => (values[keys.indexOf(key)] ?? messages.en[keys.indexOf(key)]).replace('{date}', date ?? '');
}

export function useHistoryNotice(): string {
  const { i18n } = useTranslation();
  const language = i18n.language in historyNotice ? i18n.language : i18n.language.split('-')[0];
  return historyNotice[language] ?? historyNotice.en;
}
